name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies (removed gitignore and testing uing cached node_modules)
        run: npm install

      - name: Run script to update readme quote
        run: node .github/scripts/update-readme-quote.js

      - name: Run script to update readme pokemon
        run: node .github/scripts/update-readme-pokemon.js

      - name: Run script to update my status per my twitter
        run: node .github/scripts/update-readme-status.js

      - name: Run script to set a featured follower
        run: node .github/scripts/update-readme-featured-follower.js

      - name: Run Script to update latest activity
        run: node .github/scripts/update-readme-latest-activity.js

  auto-merge-pr:
    needs: [build] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Auto merge PR if conditions are met
        env:
          GITHUB_TOKEN: ${{ secrets.README_G_TOKEN }}
        run: node .github/scripts/auto-merge-pr.js

